name: rtb
description: "Band Website"
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Routing
  go_router: ^15.2.0
  flutter_riverpod: ^2.6.1

  # Icons & SVG
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  web: ^1.1.1
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  cached_network_image: ^3.4.1
  http: ^1.4.0
  flutter_launcher_icons: ^0.14.4     # Icon-Generator
  photo_view: ^0.15.0

  # Google Fonts
  google_fonts: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/hero.jpeg
    - assets/images/members/
  fonts:
    - family: Airstream
      fonts:
        - asset: assets/fonts/AIRSTREA.ttf

# ------------------------------------------------------------
#  FLUTTER LAUNCHER ICONS - Konfiguration (Web-Icons)
# ------------------------------------------------------------
flutter_launcher_icons:
  image_path: assets/icon/icon.png       # 512×512 PNG (Quelle)

  android: false
  ios:     false
  windows:
    generate: false
  macos:
    generate: false

  web:
    generate: true
    web_location: app-icons              # Ordner heißt jetzt /app-icons/
    image_path: assets/icon/icon.png
    background_color: "#FFFFFF"          # Weißer Icon-Hintergrund
    theme_color:      "#1ED760"          # Dein PWA-Theme-Grün
