name: rtb
description: "Band Website"
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.2.0
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0

  # Für Roboto via Google Fonts
  google_fonts: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg
    - assets/images/hero.jpeg

  fonts:
    - family: Airstream
      fonts:
        # hier die Datei in assets/fonts/ airstream.ttf
        - asset: assets/fonts/AIRSTREA.ttf
